# Generated by Django 4.2.1 on 2023-09-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_elearning_delete_opportunities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='libraryitemcopy',
            name='item',
        ),
        migrations.RemoveField(
            model_name='libraryitemcopy',
            name='last_borrower',
        ),
        migrations.RemoveField(
            model_name='libraryreservation',
            name='item_copy',
        ),
        migrations.RemoveField(
            model_name='libraryreservation',
            name='student',
        ),
        migrations.DeleteModel(
            name='LibraryCategory',
        ),
        migrations.DeleteModel(
            name='LibraryItem',
        ),
        migrations.DeleteModel(
            name='LibraryItemCopy',
        ),
        migrations.DeleteModel(
            name='LibraryReservation',
        ),
    ]
