# Generated by Django 4.2.1 on 2023-09-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_libraryitem_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
