# Generated by Django 4.2.1 on 2023-09-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
