# Generated by Django 4.2.1 on 2023-09-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_block',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prevoius_school',
            new_name='primary_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_alternative_mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prevoius_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='high_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_npf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tertialy_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
