# Generated by Django 4.2.1 on 2023-09-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lever',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='shelter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
