# Generated by Django 4.2.1 on 2023-09-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_type_student_lever_student_shelter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_block',
            old_name='school_block',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='class_create',
            old_name='school_block',
            new_name='cohort',
        ),
    ]
