# Generated by Django 4.2.1 on 2023-09-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_school_block_class_block_cohort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teaching_subjects',
            new_name='teaching_units',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
    ]
