# Generated by Django 4.2.1 on 2023-09-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_teacher_email_teacher_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_picture',
        ),
    ]
