# Generated by Django 4.2.1 on 2023-09-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_exam_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaching_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
