# Generated by Django 4.2.1 on 2023-09-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ELearning',
        ),
        migrations.DeleteModel(
            name='Opportunities',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transportationroute',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='transportationstoporder',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transportationstoporder',
            name='stop',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='TransportationRequest',
        ),
        migrations.DeleteModel(
            name='TransportationRoute',
        ),
        migrations.DeleteModel(
            name='TransportationStop',
        ),
        migrations.DeleteModel(
            name='TransportationStopOrder',
        ),
    ]
