# Generated by Django 4.2.1 on 2023-09-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='ELearning',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='libraryitemcopy',
            name='item',
        ),
        migrations.RemoveField(
            model_name='libraryitemcopy',
            name='last_borrower',
        ),
        migrations.RemoveField(
            model_name='libraryreservation',
            name='item_copy',
        ),
        migrations.RemoveField(
            model_name='libraryreservation',
            name='student',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Opportunities',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='block',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transportationroute',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='transportationstoporder',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transportationstoporder',
            name='stop',
        ),
        migrations.RenameField(
            model_name='class_block',
            old_name='school_block',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='class_create',
            old_name='school_block',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_block',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prevoius_school',
            new_name='primary_school',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_alternative_mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prevoius_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_subjects',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='high_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lever',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_npf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='shelter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tertialy_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='LibraryCategory',
        ),
        migrations.DeleteModel(
            name='LibraryItem',
        ),
        migrations.DeleteModel(
            name='LibraryItemCopy',
        ),
        migrations.DeleteModel(
            name='LibraryReservation',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='TransportationRequest',
        ),
        migrations.DeleteModel(
            name='TransportationRoute',
        ),
        migrations.DeleteModel(
            name='TransportationStop',
        ),
        migrations.DeleteModel(
            name='TransportationStopOrder',
        ),
    ]
