# Generated by Django 4.2.1 on 2023-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_examresult_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
